### ISSUE TITLE
a way to query the nearest N nodes

### ISSUE THREAD

**Issue by bettdouglas** [Workiva/r_tree#31]
In the python version, there's a way to query nearest N which takes a number and returns N or less geometries. 

Can you direct me on how I can achieve that here?

**Comment by flaviocviegas** [comment]
**__**

**Comment by travissanderson-wf** [comment]
We don't have plans to add this functionality, if you wanted to look into it dart_rbush has `knn` which is what you're looking for I believe - see https://github.com/Zverik/dart_rbush/blob/6055d99c70d65fc5781ae584e837d54ec7f09947/lib/src/rbush.dart#L214

**Comment by bettdouglas** [comment]
Thanks for pointing that out. Let me test it.
